<div class="jumbotron">
    <div class="container">
        <?php echo (isset($this->alert) ? $this->alert  : ''); ?>
        <h2>Tibia OT Global</h2>
        <div class="">
            <button href="#login" data-toggle="modal" type="button" class="btn btn-success">Login</button>
            <button href="#cadastro" data-toggle="modal" type="button" class="btn btn-primary">CADASTRE-SE</button>
        </div>

        <p><span class="label label-danger" style="font-size: small;">Top 5 Guilds</span></p>
        <div class="row">
            <div class="col-sm-6 col-md-2">
                <div class="thumbnail" style="padding: 0px;">
                <img src="http://worldmusic.com.py/imgs/img/loading-bigger.gif" alt="...">
                    <div class="caption" style="margin: -3%;">
                        <h6>Nome Guild</h6>
                        <p><i class="fa fa-trophy" style="color: gold;" aria-hidden="true"></i> - Kills: 1000</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-2">
                <div class="thumbnail" style="padding: 0px;">
                <img src="http://worldmusic.com.py/imgs/img/loading-bigger.gif" alt="...">
                    <div class="caption" style="margin: -3%;">
                        <h6>Nome Guild</h6>
                        <p><i class="fa fa-trophy" style="color: silver;" aria-hidden="true"></i> - Kill: 500</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-2">
                <div class="thumbnail" style="padding: 0px;">
                <img src="http://worldmusic.com.py/imgs/img/loading-bigger.gif" alt="...">
                    <div class="caption" style="margin: -3%;">
                        <h6>Nome Guild</h6>
                        <p><i class="fa fa-trophy" style="color: #8C7853;" aria-hidden="true"></i> - Kills: 100</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-2">
                <div class="thumbnail" style="padding: 0px;">
                <img src="http://worldmusic.com.py/imgs/img/loading-bigger.gif" alt="...">
                    <div class="caption" style="margin: -3%;">
                        <h6>Nome Guild</h6>
                        <p>4 - Kills: 99</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-2">
                <div class="thumbnail" style="padding: 0px;">
                <img src="http://worldmusic.com.py/imgs/img/loading-bigger.gif" alt="...">
                    <div class="caption" style="margin: -3%;">
                        <h6>Nome Guild</h6>
                        <p>5 - Kills: 25</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>