<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu-nav" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                    <img alt="logo" style="margin: -13%" width="95" src="http://i32.tinypic.com/1fxqvm.png">
                </a>            
            </div>
            <div class="collaps navbar-collapse" id="menu-nav">
            <ul class="nav navbar-nav navbar-left">
                <li>
                    <p class="navbar-text">Você não esta logado, por favor <a href="#login" data-toggle="modal">Logue</a> ou <a href="#cadastro" data-toggle="modal">Cadastre-se</a> para demais opções.</p>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="./index">Inicio</a></li>
                <li>
                    <a href="./changelog" role="button" aria-haspopup="true" aria-expanded="false">Notas de Atualização</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Conta <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#regras" data-toggle="modal">Regras</a></li>
                        <li><a href="#recuperar" data-toggle="modal">Recuperar uma Conta</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#" role="button" aria-haspopup="true" aria-expanded="false">Ranking</a>
                </li>
                <li><a href="./shop" role="button" aria-haspopup="true" aria-expanded="false"><span class="label label-primary" style="font-size: small;">SHOP</span></a></li>
                <li><button type="button" class="btn btn-success navbar-btn">JOGAR!</button></li>
            </ul>
            </div>
        </div>
    </nav>