<div class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
    <div class="container">
        <div class="navbar-text pull-left col-md-5">
            <p>&copy Todos os Direitos reservados as respectivas marcas registradas - <?php echo date("Y"); ?></p>
        </div>
        <div class="navbar-text col-md-4">
            <span class="label label-success">Players Online: 100/500</span>
        </div>
        <div class="navbar-text pull-right col-md-1">
            <a href="#"><i class="fa fa-facebook-square fa-2x"></i></a>
            <a href="#"><i class="fa fa-twitter-square fa-2x"></i></a>
        </div>
    </div>
</div>