<div class="row">
    <div class="col-sm-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Noticias</h3>
            </div>
            <div class="panel-body">
                <?php foreach ( $view_listarNoticias as $noticia): ?>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <a href="#noticia" data-id="<?php echo $noticia['id'] ?>" data-toggle="modal" style="color: black;" class="link">
                                <div class="col-md-9">
                                    <h4><?php echo $noticia['titulo']; ?></h4>
                                    <p style="font-size: x-small">em <strong><?php echo $noticia['metatag']; ?></strong></p>
                                </div>
                                <div class="col-md-1">
                                    <img style="border-radius: 50%" width="50" height="50" src="https://static.cineclick.com.br/sites/adm/uploads/banco_imagens/31/602x0_1439644246.jpg" alt="foto" />
                                </div>
                                <div class="col-md-2" style="font-size: x-small">
                                    <h6><?php echo $noticia['account_id']; ?></h6>
                                    <span><?php echo $noticia['data_post']; ?></span>
                                </div></a>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Ranking por Level</h3>
                </div>
                <table class="table">
                    <tr>
                        <th>#</th>
                        <th>Nome</th>
                        <th>Vocação</th>
                        <th>Level</th>
                    </tr>
                    <?php foreach ($view_playerRank as $pos => $rank): ?>
                        <tr>
                            <td><?php
                                switch ($pos)
                                {
                                    case 0: echo "<i class='fa fa-trophy' style='color: gold;' aria-hidden='true'></i>"; break;
                                    case 1: echo "<i class='fa fa-trophy' style='color: silver;' aria-hidden='true'></i>"; break;
                                    case 2: echo "<i class='fa fa-trophy' style='color: #CD7F32;' aria-hidden='true'></i>"; break;
                                    default: echo $pos . "º";
                                }

                                ?>
                            </td>
                            <td><?php echo $rank['name']?></td>
                            <td><?php echo $rank['vocation']?></td>
                            <td><?php echo $rank['level']?></td>
                        </tr>
                    <?php endforeach;?>
                </table>
            </div>
        </div>
    </div>
</div>